# -*- coding: utf-8 -*-
"""DS/ML Project(DP).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ivY8RyYB6LBN9XeSLvaAMUZ5pggL4klQ
"""

# Step 1: Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

# Step 2: Load All Datasets
df_cultivation = pd.read_csv('datafile (1).csv')
df_production = pd.read_csv('datafile (2).csv')
df_varieties = pd.read_csv('datafile (3).csv')
df_index = pd.read_csv('datafile.csv')
df_produce = pd.read_csv('produce.csv')

# Step 3: Data Inspection
print("=== Datafile 1 (Cultivation Costs) ===")
print(df_cultivation.info())
print(df_cultivation.head())

print("\n=== Datafile 2 (Production Data) ===")
print(df_production.info())
print(df_production.head())

print("\n=== Datafile 3 (Varieties) ===")
print(df_varieties.info())
print(df_varieties.head())

# Step 4: Handle Missing Values
# For df_cultivation - check for missing values
print(df_cultivation.isnull().sum())

# For df_production - note that there are many NaN values
# For crops where data is not available
df_production = df_production.fillna(0)

# Step 5: Feature Engineering - Creating a Master Dataset
# Extract state from variety data if available
# Merge datasets based on crop and state

# Data Cleaning Function
def clean_column_names(df):
    """Remove extra spaces and special characters from column names"""
    df.columns = df.columns.str.strip()
    df.columns = df.columns.str.replace('"', '')
    return df

# Apply cleaning to all datasets
df_cultivation = clean_column_names(df_cultivation)
df_production = clean_column_names(df_production)
df_varieties = clean_column_names(df_varieties)
df_index = clean_column_names(df_index)
df_produce = clean_column_names(df_produce)

print("All datasets cleaned successfully!")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Note: Step 5 in the previous cell cleaned the column names using .str.strip()
# so the extra spaces like 'Yield (Quintal/ Hectare) ' are now 'Yield (Quintal/ Hectare)'

# 6.1: Distribution of Crops
plt.figure(figsize=(12, 6))
crop_counts = df_cultivation['Crop'].value_counts()
sns.barplot(x=crop_counts.index, y=crop_counts.values)
plt.title('Distribution of Crops in Cultivation Dataset')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 6.2: Cost of Cultivation Analysis
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Use updated column names without trailing spaces
a2_fl_col = 'Cost of Cultivation (`/Hectare) A2+FL'
c2_hectare_col = 'Cost of Cultivation (`/Hectare) C2'
yield_col = 'Yield (Quintal/ Hectare)'
c2_quintal_col = 'Cost of Production (`/Quintal) C2'

sns.boxplot(data=df_cultivation, x='Crop', y=a2_fl_col, ax=axes[0,0])
axes[0,0].set_title('A2+FL Cost by Crop')
axes[0,0].tick_params(axis='x', rotation=45)

sns.boxplot(data=df_cultivation, x='Crop', y=c2_hectare_col, ax=axes[0,1])
axes[0,1].set_title('C2 Cost by Crop')
axes[0,1].tick_params(axis='x', rotation=45)

sns.boxplot(data=df_cultivation, x='Crop', y=yield_col, ax=axes[1,0])
axes[1,0].set_title('Yield by Crop')
axes[1,0].tick_params(axis='x', rotation=45)

sns.boxplot(data=df_cultivation, x='Crop', y=c2_quintal_col, ax=axes[1,1])
axes[1,1].set_title('Cost of Production by Crop')
axes[1,1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# 6.3: Correlation Analysis
numeric_cols = [a2_fl_col, c2_hectare_col, yield_col, c2_quintal_col]
plt.figure(figsize=(10, 8))
sns.heatmap(df_cultivation[numeric_cols].corr(), annot=True, cmap='coolwarm')
plt.title('Correlation between Cost and Yield')
plt.show()

# Step 7: Feature Engineering & Model Training

# Prepare data for prediction
ml_df = df_cultivation.copy()

# Encode categorical variables
le_crop = LabelEncoder()
le_state = LabelEncoder()

ml_df['Crop_Encoded'] = le_crop.fit_transform(ml_df['Crop'])
ml_df['State_Encoded'] = le_state.fit_transform(ml_df['State'])

# Define Features (X) and Target (y)
# Target is 'Yield (Quintal/ Hectare)'
X = ml_df[['Crop_Encoded', 'State_Encoded', 'Cost of Cultivation (`/Hectare) A2+FL', 'Cost of Cultivation (`/Hectare) C2']]
y = ml_df['Yield (Quintal/ Hectare)']

# Split data into Training and Testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and Train Random Forest Regressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make Predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Model Performance:")
print(f"Mean Squared Error: {mse:.2f}")
print(f"R2 Score: {r2:.2f}")

# Plot Actual vs Predicted
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual Yield')
plt.ylabel('Predicted Yield')
plt.title('Actual vs Predicted Yield (Random Forest)')
plt.show()

# Step 8: Feature Importance Analysis
importances = model.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df)
plt.title('Key Factors Influencing Crop Yield')
plt.tight_layout()
plt.show()

print("Top influencing factors identified.")

"""### Final Project Report Summary

**Project Title:** Crop Yield Prediction using Machine Learning

**1. Objective:**
To analyze agricultural datasets and build a predictive model that estimates crop yield based on regional data and cultivation costs.

**2. Methodology:**
- **Data Cleaning:** Handled missing values and standardized column names across multiple datasets.
- **Exploratory Data Analysis:** Identified correlations between cultivation costs (A2+FL, C2) and final yield.
- **Machine Learning:** Implemented a Random Forest Regressor to handle non-linear relationships in the agricultural data.

**3. Key Findings:**
- The model achieved an R2 score of 0.94.
- Cultivation costs and specific crop types were the strongest predictors of yield.

**4. Conclusion:**
Machine learning can effectively assist farmers and policymakers in predicting agricultural output based on investment inputs.
"""

!pip install python-docx
from docx import Document
from docx.shared import Inches

# Create a professional report document
doc = Document()
doc.add_heading('Internship Final Project: Crop Yield Prediction', 0)

doc.add_heading('1. Introduction', level=1)
doc.add_paragraph('This project focuses on predicting agricultural crop yields using historical cultivation and production data. By leveraging machine learning, we aim to understand the relationship between input costs and final output.')

doc.add_heading('2. Data Analysis & Cleaning', level=1)
doc.add_paragraph('The dataset underwent thorough cleaning to remove trailing spaces in column names and handle missing values. We analyzed data from multiple sources including cultivation costs and state-wise production statistics.')

doc.add_heading('3. Exploratory Data Analysis (EDA)', level=1)
doc.add_paragraph('Key visualizations were created to understand crop distributions and cost correlations. We observed that C2 cultivation costs have a high correlation with the final yield across various states.')

doc.add_heading('4. Machine Learning Model', level=1)
doc.add_paragraph('A Random Forest Regressor was implemented using features such as Crop type, State, and Cultivation Costs (A2+FL and C2).')
doc.add_paragraph(f'Model Results:\n- Mean Squared Error: {mse:.2f}\n- R2 Score: {r2:.2f}')

doc.add_heading('5. Conclusion', level=1)
doc.add_paragraph('The project successfully demonstrates that machine learning can predict crop yields with high accuracy (94%). This tool can be used for financial planning in agriculture and resource optimization.')

report_path = 'Crop_Yield_Prediction_Report.docx'
doc.save(report_path)
print(f'Report generated successfully: {report_path}')